import React from "react";
import { Permissions } from "../constants";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faPieChart,
    faUser,
    faTruck,
    faUserGroup,
    faHome,
    faBoxes,
    faPrint,
    faBookmark,
    faBoxOpen,
    faMoneyCheckDollar,
    faMoneyBills,
    faQuoteRight,
    faDollarSign,
    faReceipt,
    faArrowRight,
    faFileInvoice,
    faArrowLeft,
    faEnvelope,
    faCartShopping,
    faChartColumn,
    faGear,
    faMapLocation,
    faBasketShopping,
    faSms,
    faCube,
    faFile,
    faRulerHorizontal,
    faLanguage,
    faShieldHalved,
    faLayerGroup,
    faComputer,
    faClipboardList,
    faFileInvoiceDollar,
    faGift,
    faStore,
    faCashRegister,
    faGlobe,
    faBagShopping,
} from "@fortawesome/free-solid-svg-icons";
import { getFormattedMessage } from "../shared/sharedMethod";

// Estructura del menú: en vez de acordeones anidados (excepto Reportes y
// Configuración general, que se dejan tal cual a pedido), cada pantalla es
// una entrada plana de un solo nivel, agrupada bajo encabezados
// {groupHeader: true, title} que MasterLayout.js/AsideMenu.js reconocen y
// dejan de mostrar si ninguno de sus hijos sobrevive el filtro de permisos
// (ver prepareRoutes() en MasterLayout.js).
export default [
    { groupHeader: true, title: "sidebar.group.general" },
    {
        title: "dashboard.title",
        name: "dashboard",
        fontIcon: <FontAwesomeIcon icon={faPieChart} />,
        to: "/app/dashboard",
        class: "d-flex",
        permission: Permissions.MANAGE_DASHBOARD,
        items: [
            {
                title: getFormattedMessage("dashboard.title"),
                to: "/app/dashboard",
            },
        ],
    },
    {
        title: "my-sales.title",
        name: "my-sales",
        fontIcon: <FontAwesomeIcon icon={faPieChart} />,
        to: "/app/my-sales",
        class: "d-flex",
        permission: Permissions.MANAGE_SELLER_DASHBOARD,
        items: [
            {
                title: getFormattedMessage("my-sales.title"),
                to: "/app/my-sales",
            },
        ],
    },
    {
        // Se accede desde el botón "POS" del header, no desde el sidebar --
        // class: "d-none" ya lo excluye del renderizado en AsideMenu.js.
        to: "/app/pos",
        class: "d-none",
        name: "pos",
        title: "header.pos.title",
        permission: Permissions.MANAGE_POS_SCREEN,
    },

    { groupHeader: true, title: "sidebar.group.sales" },
    {
        title: "catalog.orders.title",
        name: "catalog orders",
        fontIcon: <FontAwesomeIcon icon={faBagShopping} />,
        to: "/app/catalog-orders",
        class: "d-flex",
        permission: Permissions.MANAGE_CATALOG_ORDERS,
    },
    {
        title: "sales.title",
        name: "sales",
        fontIcon: <FontAwesomeIcon icon={faCartShopping} />,
        to: "/app/sales",
        class: "d-flex",
        permission: Permissions.MANAGE_SALE,
    },
    {
        title: "quotations.title",
        name: "quotations",
        fontIcon: <FontAwesomeIcon icon={faBasketShopping} />,
        to: "/app/quotations",
        class: "d-flex",
        permission: Permissions.MANAGE_QUOTATION,
    },
    {
        title: "sales-return.title",
        name: "sales return",
        fontIcon: <FontAwesomeIcon icon={faArrowRight} />,
        to: "/app/sale-return",
        class: "d-flex",
        permission: Permissions.MANAGE_SALE_RETURN,
    },
    {
        title: "electronic-invoices.title",
        name: "electronic invoices",
        fontIcon: <FontAwesomeIcon icon={faFileInvoiceDollar} />,
        to: "/app/electronic-invoices",
        class: "d-flex",
        permission: Permissions.MANAGE_ELECTRONIC_INVOICES,
    },
    {
        title: "credit-notes.title",
        name: "credit notes",
        fontIcon: <FontAwesomeIcon icon={faFileInvoice} />,
        to: "/app/credit-notes",
        class: "d-flex",
        permission: Permissions.MANAGE_SALE,
    },

    { groupHeader: true, title: "sidebar.group.purchases" },
    {
        title: "purchases.title",
        name: "purchases",
        fontIcon: <FontAwesomeIcon icon={faReceipt} />,
        to: "/app/purchases",
        class: "d-flex",
        permission: Permissions.MANAGE_PURCHASE,
    },
    {
        title: "purchases.return.title",
        name: "purchases return",
        fontIcon: <FontAwesomeIcon icon={faArrowLeft} />,
        to: "/app/purchase-return",
        class: "d-flex",
        permission: Permissions.MANAGE_PURCHASE_RETURN,
    },

    { groupHeader: true, title: "sidebar.group.catalog" },
    {
        title: "products.title",
        to: "/app/products",
        name: "products",
        class: "d-flex",
        fontIcon: <FontAwesomeIcon icon={faBoxes} />,
        permission: Permissions.MANAGE_PRODUCTS,
    },
    {
        title: "product.categories.title",
        name: "product categories",
        fontIcon: <FontAwesomeIcon icon={faBoxOpen} />,
        to: "/app/product-categories",
        class: "d-flex",
        permission: Permissions.MANAGE_PRODUCT_CATEGORIES,
    },
    {
        title: "variations.title",
        name: "variations",
        fontIcon: <FontAwesomeIcon icon={faLayerGroup} />,
        to: "/app/variations",
        class: "d-flex",
        permission: Permissions.MANAGE_VARIATIONS,
    },
    {
        title: "brands.title",
        name: "brands",
        fontIcon: <FontAwesomeIcon icon={faBookmark} />,
        to: "/app/brands",
        path: "/app/create-brand",
        class: "d-flex",
        permission: Permissions.MANAGE_BRANDS,
    },
    {
        title: "units.title",
        name: "units",
        fontIcon: <FontAwesomeIcon icon={faQuoteRight} />,
        to: "/app/units",
        class: "d-flex",
        permission: Permissions.MANAGE_UNITS,
    },
    {
        title: "base-units.title",
        name: "base units",
        fontIcon: <FontAwesomeIcon icon={faRulerHorizontal} />,
        to: "/app/base-units",
        class: "d-flex",
        permission: Permissions.MANAGE_UNITS,
    },
    {
        title: "print.barcode.title",
        name: "print barcode",
        fontIcon: <FontAwesomeIcon icon={faPrint} />,
        to: "/app/print/barcode",
        class: "d-flex",
        permission: Permissions.MANAGE_PRODUCTS,
    },
    {
        title: "product-kits.title",
        name: "product kits",
        fontIcon: <FontAwesomeIcon icon={faGift} />,
        to: "/app/product-kits",
        class: "d-flex",
        permission: Permissions.MANAGE_PRODUCTS,
    },

    { groupHeader: true, title: "sidebar.group.inventory" },
    {
        title: "kardex.title",
        name: "kardex",
        fontIcon: <FontAwesomeIcon icon={faClipboardList} />,
        to: "/app/kardex",
        class: "d-flex",
        permission: Permissions.MANAGE_KARDEX,
    },
    {
        title: "adjustments.title",
        name: "adjustments",
        fontIcon: <FontAwesomeIcon icon={faMapLocation} />,
        to: "/app/adjustments",
        class: "d-flex",
        permission: Permissions.MANAGE_ADJUSTMENTS,
    },
    {
        title: "transfers.title",
        name: "transfers",
        fontIcon: <FontAwesomeIcon icon={faArrowRight} />,
        to: "/app/transfers",
        class: "d-flex",
        permission: Permissions.MANAGE_TRANSFERS,
    },
    {
        title: "warehouse.title",
        name: "warehouse",
        fontIcon: <FontAwesomeIcon icon={faHome} />,
        to: "/app/warehouse",
        class: "d-flex",
        permission: Permissions.MANAGE_WAREHOUSES,
    },

    { groupHeader: true, title: "sidebar.group.expenses" },
    {
        title: "expenses.title",
        name: "expenses",
        fontIcon: <FontAwesomeIcon icon={faMoneyBills} />,
        to: "/app/expenses",
        class: "d-flex",
        permission: Permissions.MANAGE_EXPENSES,
    },
    {
        title: "expense.categories.title",
        name: "expense categories",
        fontIcon: <FontAwesomeIcon icon={faMoneyCheckDollar} />,
        class: "d-flex",
        permission: Permissions.MANAGE_EXPENSES_CATEGORIES,
        to: "/app/expense-categories",
    },
    {
        title: "cash-control.title",
        name: "cash control",
        fontIcon: <FontAwesomeIcon icon={faCashRegister} />,
        to: "/app/cash-control",
        class: "d-flex",
        permission: Permissions.CASH_CONTROL_ACCESS,
    },

    { groupHeader: true, title: "sidebar.group.people" },
    {
        title: "suppliers.title",
        name: "suppliers",
        fontIcon: <FontAwesomeIcon icon={faTruck} />,
        to: "/app/suppliers",
        class: "d-flex",
        permission: Permissions.MANAGE_SUPPLIERS,
    },
    {
        title: "customers.title",
        name: "customers",
        fontIcon: <FontAwesomeIcon icon={faUserGroup} />,
        to: "/app/customers",
        class: "d-flex",
        permission: Permissions.MANAGE_CUSTOMERS,
    },
    {
        title: "users.title",
        name: "users",
        fontIcon: <FontAwesomeIcon icon={faUser} />,
        to: "/app/users",
        class: "d-flex",
        permission: Permissions.MANAGE_USER,
    },
    {
        title: "login-logs.title",
        name: "login-logs",
        fontIcon: <FontAwesomeIcon icon={faComputer} />,
        to: "/app/login-logs",
        class: "d-flex",
        permission: Permissions.MANAGE_LOGIN_LOGS,
    },

    { groupHeader: true, title: "sidebar.group.reports" },
    {
        title: "reports.title",
        name: "reports",
        fontIcon: <FontAwesomeIcon icon={faChartColumn} />,
        to: "/app/report/report-warehouse",
        path: "/app/report/report-sale",
        stockPath: "/app/report/report-stock",
        purchasePath: "/app/report/report-purchase",
        topSellingPath: "/app/report/report-top-selling-products",
        stockDetailPath: "/app/report/report-detail-stock",
        productQuantityAlertPath: "/app/report/report-product-quantity",
        supplierReportPath: "/app/report/suppliers",
        profitLossReportPath: "/app/report/profit-loss",
        supplierReportDetailsPath: "/app/report/suppliers/details",
        bestCustomerReportPath: "/app/report/best-customers",
        customerReportPath: "/app/report/customers",
        customerReportDetailsPath: "/app/report/customers/details",
        registerReportPath: "/app/report/register",
        class: "d-flex",
        isSamePrefix: "true",
        permission: Permissions.MANAGE_REPORTS,
        subTitles: [
            { title: "warehouse.reports.title" },
            { title: "sale.reports.title" },
            { title: "stock.reports.title" },
            { title: "purchase.reports.title" },
            { title: "top-selling-product.reports.title" },
            { title: "product.quantity.alert.reports.title" },
            { title: "supplier.report.title" },
            { title: "best-customer.report.title" },
            { title: "customer.report.title" },
            { title: "customer.report.title" },
            { title: "profit-loss.reports.title" },
            { title: "best-customer.report.title" },
            { title: "register.report.title" },
        ],
        items: [
            {
                title: getFormattedMessage("warehouse.reports.title"),
                to: "/app/report/report-warehouse",
            },
            {
                title: getFormattedMessage("sale.reports.title"),
                to: "/app/report/report-sale",
            },
            {
                title: getFormattedMessage("stock.reports.title"),
                to: "/app/report/report-stock",
                detail: "/app/report/report-detail-stock",
            },
            {
                title: getFormattedMessage("purchase.reports.title"),
                to: "/app/report/report-purchase",
            },
            {
                title: getFormattedMessage("top-selling-product.reports.title"),
                to: "/app/report/report-top-selling-products",
            },
            {
                title: getFormattedMessage(
                    "product.quantity.alert.reports.title"
                ),
                to: "/app/report/report-product-quantity",
            },
            {
                title: getFormattedMessage("supplier.report.title"),
                to: "/app/report/suppliers",
                detail: "/app/report/suppliers/details",
            },
            {
                title: getFormattedMessage("profit-loss.reports.title"),
                to: "/app/report/profit-loss",
            },
            {
                title: getFormattedMessage("best-customer.report.title"),
                to: "/app/report/best-customers",
            },
            {
                title: getFormattedMessage("customer.report.title"),
                to: "/app/report/customers",
                detail: "/app/report/customers/details",
            },
            {
                title: getFormattedMessage("register.report.title"),
                to: "/app/report/register",
            },
        ],
    },
    { groupHeader: true, title: "sidebar.group.settings" },
    {
        title: "general-settings.title",
        name: "general settings",
        fontIcon: <FontAwesomeIcon icon={faGear} />,
        to: "/app/settings",
        class: "d-flex",
        is_submenu: "true",
        permission: Permissions.MANAGE_SETTING,
        subPath: {
            settingsSubPath: "/app/settings",
            prefixesSubPath: "/app/prefixes",
            mailSettingsSubPath: "/app/mail-settings",
            rolesSubPath: "/app/roles",
            storesSubPath: "/app/stores",
            catalogSettingsSubPath: "/app/catalog-settings",
            currenciesSubPath: "/app/currencies",
            languagesSubPath: "/app/languages",
            emailTemplateSubPath: "/app/email-templates",
            smsTemplateSubPath: "/app/sms-templates",
            smsApiSubPath: "/app/sms-api",
            sriConfigSubPath: "/app/sri-config",
        },
        subMenu: [
            {
                title: "settings.title",
                name: "settings",
                fontIcon: <FontAwesomeIcon icon={faGear} />,
                to: "/app/settings",
                class: "d-flex",
                permission: Permissions.MANAGE_SETTING,
            },
            {
                title: "prefix.title",
                name: "prefixes",
                fontIcon: <FontAwesomeIcon icon={faFile} />,
                to: "/app/prefixes",
                class: "d-flex",
                permission: Permissions.MANAGE_SETTING,
            },
            {
                title: "mail-settings.title",
                name: "mail settings",
                fontIcon: <FontAwesomeIcon icon={faEnvelope} />,
                to: "/app/mail-settings",
                class: "d-flex",
                permission: Permissions.MANAGE_SETTING,
            },
            {
                title: "roles.permissions.title",
                name: "roles",
                fontIcon: <FontAwesomeIcon icon={faShieldHalved} />,
                to: "/app/roles",
                class: "d-flex",
                permission: Permissions.MANAGE_ROLES,
            },
            {
                title: "store.title",
                name: "stores",
                fontIcon: <FontAwesomeIcon icon={faStore} />,
                to: "/app/stores",
                class: "d-flex",
                permission: Permissions.MANAGE_STORES,
            },
            {
                title: "catalog.virtual.title",
                name: "catalog settings",
                fontIcon: <FontAwesomeIcon icon={faGlobe} />,
                to: "/app/catalog-settings",
                class: "d-flex",
                permission: Permissions.MANAGE_STORES,
            },
            {
                title: "currencies.title",
                name: "currencies",
                fontIcon: <FontAwesomeIcon icon={faDollarSign} />,
                to: "/app/currencies",
                class: "d-flex",
                permission: Permissions.MANAGE_CURRENCY,
            },
            {
                title: "languages.title",
                name: "languages",
                fontIcon: <FontAwesomeIcon icon={faLanguage} />,
                to: "/app/languages",
                class: "d-flex",
                permission: Permissions.MANAGE_LANGUAGES,
            },
            {
                title: "email-template.title",
                name: "email-templates",
                fontIcon: <FontAwesomeIcon icon={faEnvelope} />,
                to: "/app/email-templates",
                class: "d-flex",
                permission: Permissions.MANAGE_EMAIL_TEMPLATES,
            },
            {
                title: "sms-template.title",
                name: "sms-templates",
                fontIcon: <FontAwesomeIcon icon={faSms} />,
                to: "/app/sms-templates",
                class: "d-flex",
                permission: Permissions.MANAGE_SMS_TEMPLATES,
            },
            {
                title: "sms-api.title",
                name: "sms-api",
                fontIcon: <FontAwesomeIcon icon={faCube} />,
                to: "/app/sms-api",
                class: "d-flex",
                permission: Permissions.MANAGE_SMS_API,
            },
            {
                title: "sri.settings.title",
                name: "sri settings",
                fontIcon: <FontAwesomeIcon icon={faFileInvoiceDollar} />,
                to: "/app/sri-config",
                class: "d-flex",
                permission: Permissions.MANAGE_SRI_CONFIG,
            },
        ],
    },

];
