import { Permissions } from "./constants";

/**
 * Solo path+permission de cada ruta (sin los componentes React ni los
 * imports perezosos) -- routes.js usa esta misma lista y le agrega el
 * elemento (`ele`) de cada uno por separado. Existe aparte para que
 * sharedMethod.js pueda calcular "a qué pantalla mandar a este usuario
 * según sus permisos" sin tener que importar routes.js completo (que
 * trae de arrastre todos los componentes de pantalla).
 */
export const routePermissions = [
    { path: "dashboard", permission: Permissions.MANAGE_DASHBOARD },
    { path: "my-sales", permission: Permissions.MANAGE_SELLER_DASHBOARD },
    { path: "kardex", permission: Permissions.MANAGE_KARDEX },
    { path: "electronic-invoices", permission: Permissions.MANAGE_ELECTRONIC_INVOICES },
    { path: "sri-config", permission: Permissions.MANAGE_SRI_CONFIG },
    { path: "cash-control", permission: Permissions.CASH_CONTROL_ACCESS },
    { path: "brands", permission: Permissions.MANAGE_BRANDS },
    { path: "currencies", permission: Permissions.MANAGE_CURRENCY },
    { path: "warehouse", permission: Permissions.MANAGE_WAREHOUSES },
    { path: "warehouse/create", permission: Permissions.MANAGE_WAREHOUSES },
    { path: "warehouse/edit/:id", permission: Permissions.MANAGE_WAREHOUSES },
    { path: "warehouse/detail/:id", permission: Permissions.MANAGE_WAREHOUSES },
    { path: "product-categories", permission: Permissions.MANAGE_PRODUCT_CATEGORIES },
    { path: "variations", permission: Permissions.MANAGE_VARIATIONS },
    { path: "units", permission: Permissions.MANAGE_UNITS },
    { path: "base-units", permission: Permissions.MANAGE_UNITS },
    { path: "suppliers", permission: Permissions.MANAGE_SUPPLIERS },
    { path: "suppliers/create", permission: Permissions.MANAGE_SUPPLIERS },
    { path: "suppliers/edit/:id", permission: Permissions.MANAGE_SUPPLIERS },
    { path: "customers", permission: Permissions.MANAGE_CUSTOMERS },
    { path: "customers/create", permission: Permissions.MANAGE_CUSTOMERS },
    { path: "customers/edit/:id", permission: Permissions.MANAGE_CUSTOMERS },
    { path: "users", permission: Permissions.MANAGE_USER },
    { path: "users/create", permission: Permissions.MANAGE_USER },
    { path: "users/edit/:id", permission: Permissions.MANAGE_USER },
    { path: "users/detail/:id", permission: Permissions.MANAGE_USER },
    { path: "profile/edit", permission: Permissions.MANAGE_PRODUCTS },
    { path: "products/create", permission: Permissions.MANAGE_PRODUCTS },
    { path: "products/edit/:id", permission: Permissions.MANAGE_PRODUCTS },
    { path: "products/detail/:id", permission: Permissions.MANAGE_PRODUCTS },
    { path: "adjustments", permission: Permissions.MANAGE_ADJUSTMENTS },
    { path: "adjustments/create", permission: Permissions.MANAGE_ADJUSTMENTS },
    { path: "adjustments/:id", permission: Permissions.MANAGE_ADJUSTMENTS },
    { path: "settings", permission: Permissions.MANAGE_SETTING },
    { path: "prefixes", permission: Permissions.MANAGE_SETTING },
    { path: "mail-settings", permission: Permissions.MANAGE_SETTING },
    { path: "expense-categories", permission: Permissions.MANAGE_EXPENSES_CATEGORIES },
    { path: "expenses", permission: Permissions.MANAGE_EXPENSES },
    { path: "expenses/create", permission: Permissions.MANAGE_EXPENSES },
    { path: "expenses/edit/:id", permission: Permissions.MANAGE_EXPENSES },
    { path: "purchases", permission: Permissions.MANAGE_PURCHASE },
    { path: "purchases/create", permission: Permissions.MANAGE_PURCHASE },
    { path: "purchases/edit/:id", permission: Permissions.MANAGE_PURCHASE },
    { path: "purchases/detail/:id", permission: Permissions.MANAGE_PURCHASE },
    { path: "pos", permission: Permissions.MANAGE_POS_SCREEN },
    { path: "/payment", permission: Permissions.MANAGE_USER },
    { path: "sales", permission: Permissions.MANAGE_SALE },
    { path: "sales/create", permission: Permissions.MANAGE_SALE },
    { path: "sales/edit/:id", permission: Permissions.MANAGE_SALE },
    { path: "sales/return/:id", permission: Permissions.MANAGE_SALE_RETURN },
    { path: "sales/return/edit/:id", permission: Permissions.MANAGE_SALE_RETURN },
    { path: "quotations", permission: Permissions.MANAGE_QUOTATION },
    { path: "quotations/create", permission: Permissions.MANAGE_QUOTATION },
    { path: "quotations/edit/:id", permission: Permissions.MANAGE_QUOTATION },
    { path: "quotations/Create_sale/:id", permission: Permissions.MANAGE_QUOTATION },
    { path: "quotations/detail/:id", permission: Permissions.MANAGE_QUOTATION },
    { path: "sale-return", permission: Permissions.MANAGE_SALE_RETURN },
    { path: "sale-return/edit/:id", permission: Permissions.MANAGE_SALE_RETURN },
    { path: "sale-return/detail/:id", permission: Permissions.MANAGE_SALE_RETURN },
    { path: "sales/detail/:id", permission: Permissions.MANAGE_SALE },
    { path: "purchase-return", permission: Permissions.MANAGE_PURCHASE_RETURN },
    { path: "purchase-return/create", permission: Permissions.MANAGE_PURCHASE_RETURN },
    { path: "purchase-return/edit/:id", permission: Permissions.MANAGE_PURCHASE_RETURN },
    { path: "purchase-return/detail/:id", permission: Permissions.MANAGE_PURCHASE_RETURN },
    { path: "report/report-warehouse", permission: Permissions.MANAGE_REPORTS },
    { path: "report/report-sale", permission: Permissions.MANAGE_REPORTS },
    { path: "report/report-stock", permission: Permissions.MANAGE_REPORTS },
    { path: "report/report-detail-stock/:id", permission: Permissions.MANAGE_REPORTS },
    { path: "report/report-top-selling-products", permission: Permissions.MANAGE_REPORTS },
    { path: "report/report-product-quantity", permission: Permissions.MANAGE_REPORTS },
    { path: "report/report-purchase", permission: Permissions.MANAGE_REPORTS },
    { path: "report/suppliers", permission: Permissions.MANAGE_REPORTS },
    { path: "report/profit-loss", permission: Permissions.MANAGE_REPORTS },
    { path: "report/suppliers/details/:id", permission: Permissions.MANAGE_REPORTS },
    { path: "print/barcode", permission: Permissions.MANAGE_PRODUCTS },
    { path: "roles", permission: Permissions.MANAGE_ROLES },
    { path: "roles/create", permission: Permissions.MANAGE_ROLES },
    { path: "roles/edit/:id", permission: Permissions.MANAGE_ROLES },
    { path: "transfers", permission: Permissions.MANAGE_TRANSFERS },
    { path: "transfers/create", permission: Permissions.MANAGE_TRANSFERS },
    { path: "transfers/:id", permission: Permissions.MANAGE_TRANSFERS },
    { path: "email-templates", permission: Permissions.MANAGE_EMAIL_TEMPLATES },
    { path: "email-templates/:id", permission: Permissions.MANAGE_EMAIL_TEMPLATES },
    { path: "sms-templates", permission: Permissions.MANAGE_SMS_TEMPLATES },
    { path: "sms-templates/:id", permission: Permissions.MANAGE_SMS_TEMPLATES },
    { path: "report/best-customers", permission: Permissions.MANAGE_SMS_API },
    { path: "languages", permission: Permissions.MANAGE_LANGUAGES },
    { path: "languages/:id", permission: Permissions.MANAGE_LANGUAGES },
];
